name: Run Database Scripts on Server Changes

# `on` the action of `push` (in our case, when a PR merges), when any files have
# been changed in the /server/models dir, run the jobs in sequence listed below:
on:
  push:
    branches:
      - main
    paths:
      - 'server/models/schema/**'

# The jobs, just one, called 'run-database-scripts'
jobs:
  run-database-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build backend service
        if: ${{ always() }}
        run: cd server; npm i

      - name: Remove the database
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          set -e
          npx ts-node ./server/remove_db.ts $DATABASE_URI

      - name: Populate the database
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          set -e # Stop execution on errors
          npx ts-node ./server/populate_db.ts $DATABASE_URI
