name: Run Database Scripts on Server Changes

# `on` the action of `push` (in our case, when a PR merges), when any files have
# been changed in the /server/models dir, run the jobs in sequence listed below:
on:
  push:
    branches:
      - main
    paths:
      - 'server/models/schema/**'

# The jobs, just one, called 'run-database-scripts'
jobs:
  run-database-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # The version of node we use
          node-version: '22'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./server

      # Step 4: Run the script to remove the database
      - name: Remove the database
        # Pass the Database URI securely, set up in the repository secrets in settings
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        # Stop on errors
        run: |
          set -e
          npx ts-node ./server/remove_db.ts $DATABASE_URI

      # Step 5: Run the script to populate the database
      - name: Populate the database
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          set -e # Stop execution on errors
          npx ts-node ./server/populate_db.ts $DATABASE_URI
